name: Pull Request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/continuous.yml'
    - '.github/workflows/release.yml'
    - 'README.md'

jobs:

  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Quality Control
      uses: "./.github/workflows/qc"

  Build:
    needs: QC
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Build (${{ matrix.os }})"
      uses: "./.github/workflows/build"

